/*
 * JSP generated by Resin-resin-3.1.15 (built Mon, 13 Oct 2014 03:54:20 PDT)
 */

package _jsp._customview._com._doublechaintech._retailscm;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _LoginForm__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/plain; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jstl.rt.SetLocaleTag _jsp_SetLocaleTag_0 = null;
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_SetLocaleTag_0 == null) {
        _jsp_SetLocaleTag_0 = new com.caucho.jstl.rt.SetLocaleTag();
        _jsp_SetLocaleTag_0.setPageContext(pageContext);
        _jsp_SetLocaleTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_SetLocaleTag_0.setValue("zh_CN");
      }

      _jsp_SetLocaleTag_0.doStartTag();
      out.write('\n');
      pageContext.defaultSetOrRemove("ignoreListAccessControl", java.lang.Boolean.TRUE);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_1.evalBoolean(_jsp_env)) {
        out.write(_jsp_string3, 0, _jsp_string3.length);
        if (_jsp_loop_0 == null)
          _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
        java.lang.Object _jsp_items_5 = _caucho_expr_2.evalObject(_jsp_env);
        java.util.Iterator _jsp_iter_5 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_5);
        _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
        Object _jsp_oldVar_5 = pageContext.getAttribute("item");
        while (_jsp_iter_5.hasNext()) {
          Object _jsp_i_5 = _jsp_iter_5.next();
          pageContext.setAttribute("item", _jsp_i_5);
          _jsp_loop_0.setCurrent(_jsp_i_5, _jsp_iter_5.hasNext());
          out.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_3.print(out, _jsp_env, false);
          out.write(' ');
          _caucho_expr_4.print(out, _jsp_env, false);
          out.write(_jsp_string5, 0, _jsp_string5.length);
        }
        pageContext.pageSetOrRemove("item", _jsp_oldVar_5);
        out.write(_jsp_string6, 0, _jsp_string6.length);
      }
      out.write(_jsp_string7, 0, _jsp_string7.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_SetLocaleTag_0 != null)
        _jsp_SetLocaleTag_0.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 3802963613949670813L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
    manager.addTaglibFunctions(_jsp_functionMap, "fn", "http://java.sun.com/jsp/jstl/functions");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${baseURL}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${not empty result.errorMessageList}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${result.errorMessageList}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${item.sourcePosition}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${item.body}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("customview/com/doublechaintech/retailscm/LoginForm.jsp"), -8452606341557754708L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/opt/resin-3.1.12/lib/resin.jar!/com/caucho/jstl/fmt.tld"), 8594578285720415164L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(com.caucho.jstl.rt.SetLocaleTag.class, -5807438068488217094L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;

  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string7;
  private final static char []_jsp_string4;
  private final static char []_jsp_string6;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "\n\n\n\n\n\n\n".toCharArray();
    _jsp_string3 = " \n    	 <ul>   	\n    	".toCharArray();
    _jsp_string2 = "/\" />\n	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n    \n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n    <meta name=\"description\" content=\"\">\n    <meta name=\"author\" content=\"\">\n   \n    <title>\u767b\u5f55</title>\n\n    <!-- Bootstrap core CSS -->\n    <link href=\"./bootstrap/bootstrap.min.css\" rel=\"stylesheet\">\n\n    <!-- Custom styles for this template -->\n    <link href=\"./bootstrap/signin.css\" rel=\"stylesheet\">\n  <style type=\"text/css\">* {\n text-shadow: transparent 0px 0px 0px, rgba(0,0,0,0.68) 0px 0px 0px !important; \n}</style><style id=\"style-1-cropbar-clipper\">/* Copyright 2014 Evernote Corporation. All rights reserved. */\n.en-markup-crop-options {\n    top: 18px !important;\n    left: 50% !important;\n    margin-left: -100px !important;\n    width: 200px !important;\n    border: 2px rgba(255,255,255,.38) solid !important;\n    border-radius: 4px !important;\n}\n\n.en-markup-crop-options div div:first-of-type {\n    margin-left: 0px !important;\n}\n</style>\n\n\n\n</head>\n\n  <body data-feedly-mini=\"yes\">\n\n    <div class=\"container\">\n      ".toCharArray();
    _jsp_string7 = "\n\n      <form class=\"form-signin\" method=\"post\" action=\"./secUserManager/login/userId/password/\">\n        <h2 class=\"form-signin-heading sysname\">\u8bf7\u8f93\u5165\u7528\u6237\u540d\u548c\u5bc6\u7801</h2>\n        <label for=\"inputEmail\" class=\"sr-only\">\u7528\u6237\u540d</label>\n        <input type=\"text\" id=\"inputEmail\" name=\"userId\" class=\"form-control\" placeholder=\"\u7528\u6237\u540d\" required=\"\" autofocus=\"\">\n        <label for=\"inputPassword\" class=\"sr-only\">\u5bc6\u7801</label>\n        <input type=\"password\" id=\"inputPassword\" name=\"password\" class=\"form-control\" placeholder=\"\u5bc6\u7801\" required=\"\">\n        <input type=\"hidden\" name=\"\" value=\"abcv0N0qcok4FeDLxU1rv\" required=\"\">\n        \n        <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">\u767b\u5f55</button>\n      </form>\n\n    </div> <!-- /container 	private String usernameParmeter;\n	private String passwordParmeter;-->\n\n\n    <!-- Bootstrap core JavaScript\n    ================================================== -->\n    <!-- Placed at the end of the document so the pages load faster -->\n    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\n    <script src=\"./bootstrap/ie10-viewport-bug-workaround.js\"></script>\n	<script src=\"./bootstrap/jquery.min.js\"></script>\n\n<script>\n  	\n		//alert($(location).attr('href'));\n		var oldLink=location.href;\n		var index=oldLink.indexOf(\"?__logout__\");\n		if(index>0){\n			var newLink=oldLink.substring(0,index);\n			history.pushState({}, '', newLink);\n			console.log(newLink);\n		}\n\n	\n</script>\n\n</body></html>\n\n\n\n\n\n".toCharArray();
    _jsp_string4 = "\n  		<div class=\"alert alert-danger\">\n   			".toCharArray();
    _jsp_string6 = "\n    	</ul>\n   \n    ".toCharArray();
    _jsp_string5 = "\n		</div>\n    	".toCharArray();
    _jsp_string1 = "\n\n<!DOCTYPE html>\n<!-- saved from url=(0049)http://v4-alpha.getbootstrap.com/examples/signin/ -->\n<html lang=\"en\" slick-uniqueid=\"3\">\n<head>\n\n	<base href=\"".toCharArray();
  }
}
